retargeting:
  type: position
  urdf_path: schunk_hand/schunk_svh_hand_right.urdf

  target_joint_names: [ 'right_hand_Thumb_Opposition', 'right_hand_Thumb_Flexion', 'right_hand_Index_Finger_Proximal',
                        'right_hand_Index_Finger_Distal', 'right_hand_Finger_Spread', 'right_hand_Pinky',
                        'right_hand_Ring_Finger', 'right_hand_Middle_Finger_Proximal', 'right_hand_Middle_Finger_Distal' ]
  # target_link_names: ["right_hand_base_link",
  #             "right_hand_a", "right_hand_b", "right_hand_c", "thtip",
  #             "right_hand_l", "right_hand_p", "right_hand_t", "fftip",
  #             "right_hand_k", "right_hand_o", "right_hand_s", "mftip",
  #             "right_hand_j", "right_hand_n", "right_hand_r", "rftip",
  #             "right_hand_i", "right_hand_m", "right_hand_q", "lftip"]
  target_link_names : ["thtip","mftip"]
  # target_link_human_indices: [ 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20 ]
  target_link_human_indices : [4,12]
  add_dummy_free_joint: False

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  # 1 means no filter while 0 means not moving
  low_pass_alpha: 0.5
