retargeting:
  type: vector
  urdf_path: schunk_hand/schunk_svh_hand_right.urdf

  # Target refers to the retargeting target, which is the robot hand
  # target_joint_names: [ 'right_hand_Thumb_Opposition', 'right_hand_Thumb_Flexion', 'right_hand_Index_Finger_Proximal',
  #                       'right_hand_Index_Finger_Distal', 'right_hand_Finger_Spread', 'right_hand_Pinky',
  #                       'right_hand_Ring_Finger', 'right_hand_Middle_Finger_Proximal', 'right_hand_Middle_Finger_Distal']
  target_joint_names: ['right_hand_Thumb_Opposition', 'right_hand_Thumb_Flexion', 'right_hand_j3', 'right_hand_j4', 
    'right_hand_index_spread', 'right_hand_Index_Finger_Proximal', 'right_hand_Index_Finger_Distal', 
    'right_hand_j14', 'right_hand_j5', 'right_hand_Finger_Spread', 'right_hand_Pinky', 
    'right_hand_j13', 'right_hand_j17', 'right_hand_ring_spread', 'right_hand_Ring_Finger', 'right_hand_j12', 'right_hand_j16', 
    'right_hand_Middle_Finger_Proximal', 'right_hand_Middle_Finger_Distal', 'right_hand_j15']

  target_origin_link_names: ["right_hand_base_link", "right_hand_base_link", "right_hand_base_link", "right_hand_base_link", "right_hand_base_link"]
  target_task_link_names: ["thtip", "fftip", "mftip", "rftip", "lftip"]
  # scaling_factor: [0.8, 1.0, 1.5]
  scaling_factor: [1.0, 1.0, 1.0]

  # Source refers to the retargeting input, which usually corresponds to the human hand
  # The joint indices of human hand joint which corresponds to each link in the target_link_names
  # target_link_human_indices: [ [ 0,0,0,0,0, 1,5,9,13,17, 2,6,10,14,18, 3,7,11,15,19 ], 
  #                              [ 1,5,9,13,17, 2,6,10,14,18, 3,7,11,15,19, 4,8,12,16,20 ] ]
  target_link_human_indices: [ [ 0,0,0 ], [ 4,12,16 ] ]
  # target_link_human_indices: [[0,0,0,0,0, 2,6,10,14,18], [2,6,10,14,18, 4,8,12,16,20]]
  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 0.5
  ignore_mimic_joint: True
  # add_dummy_free_joint: False
